import {vi} from 'vitest'


export function createMockGL () {
    return {
        enable: () => {},
        disable: () => {},
        blendFunc: () => {},
        viewport: () => {},
        clearColor: () => {},
        clear: () => {},
        createBuffer: () => ({}),
        createTexture: () => ({}),
        createProgram: () => ({}),
        createShader: () => ({}),
        shaderSource: () => {},
        compileShader: () => {},
        getShaderParameter: () => true,
        getShaderInfoLog: () => '',
        attachShader: () => {},
        linkProgram: () => {},
        getProgramParameter: () => true,
        getProgramInfoLog: () => '',
        deleteShader: () => {},
        useProgram: () => {},
        getUniformLocation: () => ({}),
        getAttribLocation: () => 0,
        bindBuffer: () => {},
        bufferData: () => {},
        enableVertexAttribArray: () => {},
        disableVertexAttribArray: () => {},
        vertexAttribPointer: () => {},
        uniformMatrix3fv: () => {},
        uniform1i: () => {},
        uniform1f: () => {},
        uniform2f: () => {},
        uniform3f: () => {},
        uniform4f: () => {},
        uniformMatrix4fv: () => {},
        drawArrays: () => {},
        drawElements: () => {},
        deleteBuffer: () => {},
        deleteProgram: () => {},
        deleteTexture: () => {},
        bindTexture: () => {},
        texImage2D: () => {},
        texParameteri: () => {},
        activeTexture: () => {},
        createFramebuffer: () => ({}),
        bindFramebuffer: () => {},
        framebufferTexture2D: () => {},
        framebufferRenderbuffer: () => {},
        checkFramebufferStatus: () => 36053,
        deleteFramebuffer: () => {},
        lineWidth: () => {},
        createRenderbuffer: () => ({}),
        bindRenderbuffer: () => {},
        renderbufferStorageMultisample: () => {},
        deleteRenderbuffer: () => {},
        blitFramebuffer: () => {},
        getParameter: (param) => {

            if (param === 0x8d57) {
                return 4
            }
            return 4
        },

        BLEND: 1,
        SRC_ALPHA: 1,
        ONE_MINUS_SRC_ALPHA: 1,
        TEXTURE_2D: 1,
        TEXTURE0: 1,
        RGBA: 1,
        UNSIGNED_BYTE: 1,
        LINEAR: 1,
        CLAMP_TO_EDGE: 1,
        TEXTURE_MIN_FILTER: 1,
        TEXTURE_MAG_FILTER: 1,
        TEXTURE_WRAP_S: 1,
        TEXTURE_WRAP_T: 1,
        FRAMEBUFFER: 1,
        COLOR_ATTACHMENT0: 1,
        COLOR_BUFFER_BIT: 1,
        VERTEX_SHADER: 1,
        FRAGMENT_SHADER: 1,
        ARRAY_BUFFER: 1,
        ELEMENT_ARRAY_BUFFER: 1,
        FLOAT: 1,
        UNSIGNED_SHORT: 1,
        TRIANGLES: 1,
        TRIANGLE_FAN: 1,
        TRIANGLE_STRIP: 1,
        LINES: 1,
        DYNAMIC_DRAW: 1,
        STATIC_DRAW: 1,
        COMPILE_STATUS: 1,
        LINK_STATUS: 1,
        FRAMEBUFFER_COMPLETE: 36053,
        RENDERBUFFER: 1,
        RGBA8: 1,
        READ_FRAMEBUFFER: 1,
        DRAW_FRAMEBUFFER: 1,
        MAX_SAMPLES: 0x8d57,
        NEAREST: 1
    }
}


export function createMockGLWithSpies () {
    return {
        enable: vi.fn(),
        disable: vi.fn(),
        blendFunc: vi.fn(),
        viewport: vi.fn(),
        clearColor: vi.fn(),
        clear: vi.fn(),
        createBuffer: vi.fn(() => ({})),
        createTexture: vi.fn(() => ({})),
        createProgram: vi.fn(() => ({})),
        createShader: vi.fn(() => ({})),
        shaderSource: vi.fn(),
        compileShader: vi.fn(),
        getShaderParameter: vi.fn(() => true),
        getShaderInfoLog: vi.fn(() => ''),
        attachShader: vi.fn(),
        linkProgram: vi.fn(),
        getProgramParameter: vi.fn(() => true),
        getProgramInfoLog: vi.fn(() => ''),
        deleteShader: vi.fn(),
        useProgram: vi.fn(),
        getUniformLocation: vi.fn(() => ({})),
        getAttribLocation: vi.fn(() => 0),
        bindBuffer: vi.fn(),
        bufferData: vi.fn(),
        enableVertexAttribArray: vi.fn(),
        disableVertexAttribArray: vi.fn(),
        vertexAttribPointer: vi.fn(),
        uniformMatrix3fv: vi.fn(),
        uniform1i: vi.fn(),
        uniform1f: vi.fn(),
        uniform2f: vi.fn(),
        uniform3f: vi.fn(),
        uniform4f: vi.fn(),
        uniformMatrix4fv: vi.fn(),
        drawArrays: vi.fn(),
        drawElements: vi.fn(),
        deleteBuffer: vi.fn(),
        deleteProgram: vi.fn(),
        deleteTexture: vi.fn(),
        bindTexture: vi.fn(),
        texImage2D: vi.fn(),
        texParameteri: vi.fn(),
        activeTexture: vi.fn(),
        createFramebuffer: vi.fn(() => ({})),
        bindFramebuffer: vi.fn(),
        framebufferTexture2D: vi.fn(),
        framebufferRenderbuffer: vi.fn(),
        checkFramebufferStatus: vi.fn(() => 36053),
        deleteFramebuffer: vi.fn(),
        lineWidth: vi.fn(),
        createRenderbuffer: vi.fn(() => ({})),
        bindRenderbuffer: vi.fn(),
        renderbufferStorageMultisample: vi.fn(),
        deleteRenderbuffer: vi.fn(),
        blitFramebuffer: vi.fn(),
        getParameter: vi.fn((param) => {
            if (param === 0x8d57) {
                return 4
            }
            return 4
        }),

        BLEND: 1,
        SRC_ALPHA: 1,
        ONE_MINUS_SRC_ALPHA: 1,
        TEXTURE_2D: 1,
        TEXTURE0: 1,
        RGBA: 1,
        UNSIGNED_BYTE: 1,
        LINEAR: 1,
        CLAMP_TO_EDGE: 1,
        TEXTURE_MIN_FILTER: 1,
        TEXTURE_MAG_FILTER: 1,
        TEXTURE_WRAP_S: 1,
        TEXTURE_WRAP_T: 1,
        FRAMEBUFFER: 1,
        COLOR_ATTACHMENT0: 1,
        COLOR_BUFFER_BIT: 1,
        VERTEX_SHADER: 1,
        FRAGMENT_SHADER: 1,
        ARRAY_BUFFER: 1,
        ELEMENT_ARRAY_BUFFER: 1,
        FLOAT: 1,
        UNSIGNED_SHORT: 1,
        TRIANGLES: 1,
        TRIANGLE_FAN: 1,
        TRIANGLE_STRIP: 1,
        LINES: 1,
        DYNAMIC_DRAW: 1,
        STATIC_DRAW: 1,
        COMPILE_STATUS: 1,
        LINK_STATUS: 1,
        FRAMEBUFFER_COMPLETE: 36053,
        RENDERBUFFER: 1,
        RGBA8: 1,
        READ_FRAMEBUFFER: 1,
        DRAW_FRAMEBUFFER: 1,
        MAX_SAMPLES: 0x8d57,
        NEAREST: 1
    }
}


export function createMockImage (width = 100, height = 100, {complete = true} = {}) {
    return {
        width,
        height,
        complete,
        naturalWidth: complete ? width : 0,
        naturalHeight: complete ? height : 0
    }
}


export function createMockCanvas (width = 800, height = 600) {
    const canvas = document.createElement('canvas')
    canvas.width = width
    canvas.height = height
    return canvas
}
